#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev
    
server:
  port: 4001
spring:
  profiles: dev
    application:
      name: microservice-config-dev
      
server:
  port: 4002
spring:
  profiles: prod
    application:
      name: microservice-config-prod
#保存时注意，选择 UTF-8 保存
